### PR TITLE
Release current version of the theme and publish on RubyGems

### PR DESCRIPTION
**Pull request by chrisguindon**
Signed-off-by: Christopher Guindon <chris.guindon@eclipse-foundation.org>

### CODE REVIEW

**Comment by chrisguindon** [comment]
@jgallimore,

I am currently working on a PR to resolve the deployment issue on RubyGems. I was thinking of naming the gem "eclipsefdn-jekyll-theme-jakarta-ee" to be consistent with what we do on NPM:
https://www.npmjs.com/package/eclipsefdn-hugo-solstice-theme

Would you prefer to keep it the same name as the repo "jekyll-theme-jakarta-ee"?

If we do change it, I assume that I will need to rename and update the spec.name property for the jekyll-theme-jakarta-ee.gemspec file.

**Comment by chrisguindon** [comment]
Hi @jgallimore ,

do you have a preference here? 

If you think this rename will cause some extra work, I can revert some of my change and deploy the gem as jekyll-theme-jakarta-ee.

**Comment by jgallimore** [comment]
No strong opinion on the name here, but there's at least 2 projects, using it now (maybe more), so we need to be a little careful there. If we don't keep the repo name, I think we'll be ok in that respect.

Is having an API key in the source code secure?

**Comment by chrisguindon** [comment]
@jgallimore,

Thanks for the feedback! +1 for not breaking anything. I will try to deploy the gem using the name of the repo.

The api keys are encrypted:
https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml

**Comment by chrisguindon** [comment]
jekyll-theme-jakarta-ee@0.1.2 has been pushed to rubygems.org:
https://rubygems.org/gems/jekyll-theme-jakarta-ee

**Comment by chrisguindon** [comment]
@jgallimore If you prefer, I can remove the api_key and from .travis file and add it via the travis-ci configuration page. 

I did notice that the travis gem does the same thing:
https://github.com/travis-ci/travis.rb/blob/master/.travis.yml

**Pull request merged**
